name: Generate M3U Playlist
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # 12 saatte bir

jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Create config files
      run: |
        # Config dosyasını oluştur
        cat > scripts/api-config.json << 'EOF'
        {
          "mainUrl": "https://m.prectv55.lol",
          "swKey": "4F5A9C3D9A86FA54EACEDDD635185/64f9535b-bd2e-4483-b234-89060b1e631c",
          "userAgent": "Dart/3.7 (dart:io)",
          "referer": "https://twitter.com/"
        }
        EOF
        
        echo "Config dosyası oluşturuldu:"
        cat scripts/api-config.json

    - name: Generate M3U
      run: |
        cd scripts
        php generate-m3u.php

    - name: Commit and Push M3U
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add m3u-output/rectv-playlist.m3u
        git commit -m "Auto-update M3U playlist $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push
